{{- if .Values.mongoVolumes.enabled }}
{{- $storageClass := .Values.mongoVolumes.storageClassName }}
{{- $size := .Values.mongoVolumes.storageSize }}
{{- $reclaim := .Values.mongoVolumes.reclaimPolicy }}
{{- $nfsServer := .Values.mongoVolumes.nfsServer }}
{{- $basePath := .Values.mongoVolumes.basePath }}
{{- $replicas := int .Values.mongoVolumes.replicas }}

{{- range $i := until $replicas }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  mongo-data-my-final-todo-list-mongo-{{ $i }}
spec:
  capacity:
    storage: {{ $size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ $reclaim }}
  storageClassName: {{ $storageClass }}
  nfs:
    path: {{ printf "%s/mongo-%d" $basePath $i }}
    server: {{ $nfsServer }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-my-final-todo-list-mongo-{{ $i }}
spec:
  volumeName: mongo-data-my-final-todo-list-mongo-{{ $i }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $size }}
  storageClassName: ""
{{- end }}
{{- end }}

