apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list.fullname" . }}-mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo

