apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "todo-list.fullname" . }}-mongo-init
  labels:
    app: mongo
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongo-init
          image: mongo:6.0
          command: ["mongosh"]
          args:
            - "mongodb://{{ include "todo-list.fullname" . }}-mongo-0.{{ include "todo-list.fullname" . }}-mongo:27017"
            - "--eval"
            - |
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "{{ include "todo-list.fullname" . }}-mongo-0.{{ include "todo-list.fullname" . }}-mongo:27017" },
                  { _id: 1, host: "{{ include "todo-list.fullname" . }}-mongo-1.{{ include "todo-list.fullname" . }}-mongo:27017" },
                  { _id: 2, host: "{{ include "todo-list.fullname" . }}-mongo-2.{{ include "todo-list.fullname" . }}-mongo:27017" }
                ]
              });
  backoffLimit: 1

