apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-list.fullname" . }}-nodejs
  labels:
    app: todos-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-nodejs
  template:
    metadata:
      labels:
        app: todos-nodejs
    spec:
      initContainers:
        - name: wait-for-mongo-init
          image: mongo:6.0
          command: [ "sh", "-c" ]
          args:
            - |
              echo "Waiting for MongoDB primary (mongo-0) to be ready..."
              until mongosh "mongodb://{{ include "todo-list.fullname" . }}-mongo-0.{{ include "todo-list.fullname" . }}-mongo:27017" --eval "db.runCommand({ ping: 1 })" > /dev/null 2>&1; do
                echo "MongoDB not ready yet. Sleeping 5s..."
                sleep 5
              done
      containers:
        - name: todos-nodejs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4000
          env:
            - name: mongoDbUrl
              value: "mongodb://my-final-todo-list-mongo:27017/todolistDb"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

