apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-nodejs
  template:
    metadata:
      labels:
        app: todos-nodejs
    spec:
      containers:
        - name: todos-nodejs
          image: docker.io/abdallahelaraby/myapp:some-tag
          ports:
            - containerPort: 4000
          env:
            - name: mongoDbUrl
              value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/todolistDb?replicaSet=rs0"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: todos-service
spec:
  type: NodePort
  selector:
    app: todos-nodejs
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080  
